### ISSUE TITLE
Re-evaluating code fails

### ISSUE THREAD

**Issue by bthj** [mimic-sussex/sema#183]
After initial load of the Sema UI, evaluating and running code from the LiveCode Editor, sound is played as expected, but after stopping with `cmd-.` and starting again with `cmd-Enter`, a short click is heard and then no more.  Please see the attached screen recording.

As it seems no one else has been reporting this issue, it likely has something to do with my setup? 

macOS 10.15.6 (19G73) (with the BlackHole Virtual Audio Driver installed)
Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)

[Screen Recording 2020-07-19 at 20.54.52.mov.zip](https://github.com/mimic-sussex/sema/files/4944773/Screen.Recording.2020-07-19.at.20.54.52.mov.zip)

**Comment by frantic0** [comment]
Thanks for reporting the issue, @bthj. 

It is not your setup, I can reproduce it. We will be looking into that soon.

**Comment by frantic0** [comment]
Hi, 

I just fixed the bug that was 'choking' the audio engine playback.

the problem was twofold and affected the code hot-swap mechanism both in the crossfade and normal playback.  

The snippet below is accessing `inputs` incorrectly and passed on an *undefined* to signals, compromising the current signal function.  

```
					try {

						this.signals[this.currentSignalFunction](
							this._q[this.currentSignalFunction],
							inputs[0][0][i],                                                                           // BUG - part 1
							this._mems[this.currentSignalFunction]
						);

					} catch (err) {
						console.log("EVAL ERROR – NO xfading ", err);
						console.log("signals: ", this.signals);
						console.log("currentSignalFunction: ", this.currentSignalFunction);
						console.log(
							"_q[currentSignalFunction]: ",
							this._q[this.currentSignalFunction]
						);
						console.log("inputs: ", inputs);
						console.log("mems: ", this._mems);

					        this.signals[this.currentSignalFunction] = (x, y, z) => {                 // BUG - part 2
						   return 0;
						};
```

This also caused an exception to be thrown and caught. In the catch, the current signal function is replaced by a silence function, which double chocked the engine.

Another problem is that the exception is misleading. There is no EVAL going on here. 

Plenty of housekeeping to do here

Best,
FØ
